name: enjoy_cafe_app
description: Enjoy Cafe Points
environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.0.0
  firebase_database: ^12.0.0
  flutter_tts: ^4.2.3
  google_fonts: ^6.2.1
  flutter_fortune_wheel: ^1.3.2
  flutter_launcher_icons: ^0.14.4
  lottie: ^2.3.0
  audioplayers: ^6.5.1
  intl: ^0.18.1   # <-- เพิ่มบรรทัดนี้

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/cup.png
    - assets/icon.png
    - assets/A fitness cow.json
    - assets/Success.json
    - assets/girl-hey-ringtone.mp3   # <-- เพิ่มไฟล์เสียงด้วย

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
